name: Build-MacOS

on: [push]

env:
  BUILD_TYPE: Release
  HASH_MAP: USE_TSL_ROBIN_MAP

jobs:
  build:
    runs-on: [ macos-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive

      - name: Install dependencies
        run: brew install boost

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DHASH_MAP=$HASH_MAP

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: (cd tests; ctest -C $BUILD_TYPE)
