name: build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build-ipk:
    name: ${{matrix.buildname}}

    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-20.04, macos-13, macos-12 ]
        include:
          - os: ubuntu-22.04
            buildname: 'ubuntu-22.04'
            triplet: x64-linux
            compiler: gcc_64
          - os: ubuntu-20.04
            buildname: 'ubuntu-20.04'
            triplet: x64-linux
            compiler: gcc_64
          - os: macos-13
            buildname: 'macos-13'
            triplet: x64-osx
            compiler: clang_64
          - os: macos-12
            buildname: 'macos-12'
            triplet: x64-osx
            compiler: clang_64

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: (MacOS) Install dependencies
        if: runner.os == 'macOS'
        run: brew update && brew install cmake boost zlib && pip3 install click

      - name: (Linux) Install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -yq libboost-dev libboost-serialization-dev libboost-filesystem-dev libboost-iostreams-dev libboost-program-options-dev zlib1g-dev

      - name: (MacOS) Download RAxML-ng
        if: runner.os == 'macOS'
        run: wget https://github.com/amkozlov/raxml-ng/releases/download/1.2.0/raxml-ng_v1.2.0_macos_x86_64.zip && unzip raxml-ng_v1.2.0_macos_x86_64.zip

      - name: (Linux) Download RAxML-ng
        if: runner.os == 'Linux'
        run: wget https://github.com/amkozlov/raxml-ng/releases/download/1.2.0/raxml-ng_v1.2.0_linux_x86_64.zip && unzip raxml-ng_v1.2.0_linux_x86_64.zip

      - name: Configure CMake
        run: cmake -B ${{runner.workspace}}/bin -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{runner.workspace}}/bin --config $BUILD_TYPE -j ${{ steps.cpu-cores.outputs.count }}

      - name: Test build successful
        run: test -f ${{runner.workspace}}/bin/ipk/ipk-dna && test -f ${{runner.workspace}}/bin/ipk/ipk-aa

      - name: Test python script
        run: python3 ipk.py build --help

      - name: Build tools
        run: cmake --build ${{runner.workspace}}/bin --config $BUILD_TYPE --target diff-dna diff-aa -j ${{ steps.cpu-cores.outputs.count }}

      - name: Test
        run: pwd && ls && echo "OK" && ls ../ && echo "OK ${{runner.workspace}}" && ls ${{runner.workspace}}

      - name: Test database build
        run: bash tests/test-db-build.sh ${{runner.workspace}} ${{runner.workspace}}/IPK/raxml-ng

